LMBishop/Quests

- src/me/fatpigsarefat/quests/Quests.java
- src/me/fatpigsarefat/quests/quests/tasktypes/types/PlaytimeTaskType.java
> Playtime Quest

- .classpath
- .gitignore
- .project
- .settings/org.eclipse.jdt.core.prefs
- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/BreedingTaskType.java
- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/ExpEarnTaskType.java
- breeding quest task
- exp earn quest type
> New tasks: breeding and xpearn

- src/main/java/com/leonardobishop/quests/commands/CommandQuests.java
- src/main/java/com/leonardobishop/quests/obj/Messages.java
- src/main/resources/config.yml
- Now the command **/quests q** is like this: **/quests q/quest questid <start/cancel>**
- Added a message if a subcommand doesn't exist.
> Added option for cancel quests by command

- README.md
- src/main/java/com/leonardobishop/quests/obj/Items.java
- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/BreedingTaskType.java
- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/DealDamageTaskType.java
- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/EnchantingTaskType.java
- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/ExpEarnTaskType.java
- src/main/java/com/leonardobishop/quests/title/Title.java
Replaced all tabs with 4 spaces to match the contribution guidelines from readme
Also fixed some typos in readme
> Change indentation from tabs to spaces

- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/MiningCertainTaskType.java
For MiningCertainTaskType the configuration now has an alias for 'block' as 'blocks'. It now also supports multiple blocks for the mining certain, and supports the use of no data configuration input but instead the data on the line.
For instance,
```
tasks:
blockbreakc:
type: "blockbreakcertain"
amount: 30
blocks:
- COBBLESTONE
- LOG:1 # :1 for spruce
- STONE:2 # :2 for polished andesite
- WOOL:5 # :5 for lime wool
data: 0 # will act as fallback if data isn't specified
reverse-if-placed: false
use-similar-blocks: false
```
> Added option for multiple blocks with individual data

- src/main/java/com/leonardobishop/quests/quests/tasktypes/types/MiningCertainTaskType.java
This allows you to do this kind of configuration https://pics.edensky.fr/2021-02/06/14-01_mv6I.png
> improv. fix multiple datas

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/command/QuestCommandHandler.java
- Return if quest id arg is invalid
- Tab complete quests instead of categories
- Change usage message to reflect real usage
> Fix quest command's behavior

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BuildingCertainTaskType.java
Fixes #322
https://github.com/LMBishop/Quests/blob/ad8cbad7cc90531922f5d68b8be621d18b2b1b3b/bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BuildingCertainTaskType.java#L65
> Fix reverse-in-broken for BuildingCertainTaskType

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/InventoryTaskType.java
#367 - Unfortunately PlayerBucketEvent is an abstract class D:
> Fix inventory task type's IllegalPluginAccessException 

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/FarmingCertainTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/FarmingTaskType.java
Fixes https://github.com/LMBishop/Quests/issues/363
> Add farming task type modes for harvestable blocks support

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/WalkingTaskType.java
Fixes https://github.com/LMBishop/Quests/issues/358 and many other possible issues
> Fix transport method validation

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/BukkitQuestsPlugin.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/TamingCertainTaskType.java
Closes https://github.com/LMBishop/Quests/issues/377
> Add taming certain task type

- bukkit/src/main/resources/plugin.yml
Fixes https://github.com/LMBishop/Quests/issues/397
> Fix plugin dependent task types

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/DistancefromTaskType.java
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Location.html#distanceSquared(org.bukkit.Location)
> Fix IAE in DistancefromTaskType

- bukkit/build.gradle
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/PaginatedQMenu.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/QMenu.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/itemstack/QItemStack.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/storage/MySqlStorageProvider.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/EssentialsBalanceTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/EssentialsMoneyEarnTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/ShopGUIPlusBuyTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/ShopGUIPlusSellTaskType.java
Closes https://github.com/LMBishop/Quests/issues/497
Closes https://github.com/LMBishop/Quests/issues/496
Closes https://github.com/LMBishop/Quests/issues/488
Closes https://github.com/LMBishop/Quests/issues/468
Closes https://github.com/LMBishop/Quests/issues/457
Closes https://github.com/LMBishop/Quests/issues/290
> Fix 1.8.8 support, fix ShopGUI+ and Essentials task types

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/scheduler/folia/FoliaServerScheduler.java
This issue seeks to fix issues when running tasks with a delay lesser or equal to zero!
> Fix issues with delay ticks for Folia scheduler

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BlockshearingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BreedingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BrewingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BucketInteractionTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BuildingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/CommandTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/ConsumeTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/CraftingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/DealDamageTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/DistancefromTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/FarmingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/FishingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/InteractTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/InventoryTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/MilkingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/MiningTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/MobkillingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/PlayerkillingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/ReplenishingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/ShearingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/SmeltingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/SmithingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/TamingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/WalkingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/ShopGUIPlusBuyTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/ShopGUIPlusInteractionTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/ShopGUIPlusSellTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/TaskUtils.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/constraint/TaskConstraint.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/constraint/TaskConstraintSet.java
A (probably) better replacement for reverted https://github.com/LMBishop/Quests/commit/7a7298e91cf53af8697a699bb4d015102d38e3ae
Going to test performance of that solution soon:tm:
> Better task constraints implementation

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/config/BukkitQuestsLoader.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/questcontroller/NormalQuestController.java
- common/src/main/java/com/leonardobishop/quests/common/quest/Quest.java
Partially closes https://github.com/LMBishop/Quests/issues/558
> Add cancel commands

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/coreprotect/CoreProtectHook.java
Closes https://github.com/LMBishop/Quests/issues/162
> Fix CoreProtect delay caused by queue

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/config/BukkitQuestsLoader.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/itemgetter/ItemGetter14.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/NamespacedKeyUtils.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/SoundUtils.java
Closes https://github.com/LMBishop/Quests/issues/585
Closes https://github.com/LMBishop/Quests/issues/583
> Add namespaced sounds and types support

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/CancelQMenu.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/PaginatedQMenu.java
- bukkit/src/main/resources/resources/bukkit/config.yml
> Add PlaceholderAPI support in GUI titles

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/StartedQMenu.java
- bukkit/src/main/resources/resources/bukkit/config.yml
- docs/configuration/custom-gui-items.md
> Support custom elements in started quests menu

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/PlaceholderAPIEvaluateTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/TaskUtils.java
- bukkit/src/main/resources/resources/bukkit/config.yml
Closes https://github.com/LMBishop/Quests/issues/547
> Add async option in PAPI task type

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/CustomMenuElement.java
Closes https://github.com/LMBishop/Quests/issues/601
> Ensure that custom menu element commands are ran from Folia GlobalTickThread

- bukkit/build.gradle
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/BukkitQuestsPlugin.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/itemgetter/ItemGetter13.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/itemgetter/ItemGetter14.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/itemgetter/ItemGetter8.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/chat/Chat.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/chat/CodedColorAdapter.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/chat/ColorAdapter.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/chat/HexColorAdapter.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/chat/MiniMessageParser.java
(don't even know why would one use craftbukkit these times but why not to fix that lol)
> Fix CraftBukkit compatibility

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/MobkillingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/TaskUtils.java
- common/src/main/java/com/leonardobishop/quests/common/config/ConfigProblemDescriptions.java
Closes https://github.com/LMBishop/Quests/issues/460
> Add spawn reason option to mob killing task type

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/BukkitQuestsPlugin.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/versionspecific/VersionSpecificHandler.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/versionspecific/VersionSpecificHandler17.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/versionspecific/VersionSpecificHandler8.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/MilkingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/MobkillingTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/TaskUtils.java
Fixes https://github.com/LMBishop/Quests/issues/620 (ignore baby mobs)
Closes https://github.com/LMBishop/Quests/issues/607 (goat support)
> Fix baby cow milking, add goat support

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/ZNPCsPlusDeliverTaskType.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/ZNPCsPlusInteractTaskType.java
Closes https://github.com/LMBishop/Quests/issues/618
(can be merged without conflicts with other PRs)
> Ignore ZNPCsPlus hologram serialization errors

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/TaskUtils.java
Do not init it at all if not required
> Delay Legacy Material Support initialization

- common/src/main/java/com/leonardobishop/quests/common/player/questprogressfile/TaskProgress.java
Closes https://github.com/LMBishop/Quests/issues/543
> Fix almost unreproducible rewards dupe on completion

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/papi/QuestsPlaceholders.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/Messages.java
Fixes https://github.com/LMBishop/Quests/issues/669
> Do not return null for a negative cooldown placeholder

- .github/workflows/build.yml
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/BukkitQuestsPlugin.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/BarteringTaskType.java
- docs/task-types/bartering-(task-type).md
Compatible with Spigot 1.16.5+
> Add bartering task type

- jitpack.yml
It enables people to use jitpack for latest Quests dependency
> Add jitpack.yml for proper jitpack support

- bukkit/build.gradle.kts
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/BukkitQuestsPlugin.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/BedWars1058BedBreakTask.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/BedWars1058FinalKillTask.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/BedWars1058LoseTask.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/dependent/BedWars1058WinTask.java
- bukkit/src/main/resources/plugin.yml
- docs/task-types/bedwars1058_bedbreak-(task-type).md
- docs/task-types/bedwars1058_finalkill-(task-type).md
- docs/task-types/bedwars1058_lose-(task-type).md
- docs/task-types/bedwars1058_win-(task-type).md
I added compatibility for BedWars1058 and created 4 new task: Bed Break, Final Kill, Win, and Lose
> Add BedWars1058 compatibility

- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/CancelQMenu.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/MenuController.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/PaginatedQMenu.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/AbortCancelMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/BackMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/CategoryMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/ConfirmCancelMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/CustomMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/MenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/PageDescMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/PageNextMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/PagePrevMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/QuestMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/element/SpacerMenuElement.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/questcontroller/NormalQuestController.java
- bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/DispatchUtils.java
- docs/configuration/creating-a-quest.md
Closes https://github.com/LMBishop/Quests/issues/470
> Add option to dispatch player commands
